"""Shared core types: ``Claim``, ``Concept``, and ``Source``.

Field definitions follow docs/llm-yuki-v0.1-proposal/ARCHITECTURE.md §1.2/§1.3/§1.5 (sourced from decision D9
and its 2026-08-25 follow-up, and D21's 2026-08-27 addition of this third type, originally implemented under
the name ``Document`` and renamed to ``Source`` to match the naming ``nashsu/llm_wiki`` (D21's inspiration)
itself uses). These are the three OKF typed-frontmatter types every domain shares; a per-corpus skill may add
its own extension types on top (e.g. ``sci-paper:Paper``), but the core pipeline only ever needs to
understand ``Claim``/``Concept``/``Source``.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field

ProvenanceState = Literal["extracted", "merged", "inferred", "ambiguous"]
"""How a Claim came to exist — see D9 supplementary decision for how this feeds root-cause attribution."""


class ContradictionRef(BaseModel):
    """One entry of ``Claim.contradicted_by``: a candidate conflict with another Claim.

    This is a lint *candidate/accelerator*, not an authoritative judgment — the Validator must still run its
    own full contradiction sweep (proposal ARCHITECTURE.md §1.2, "⚠️ 這個欄位是 lint 的候選線索/加速器").
    """

    slug: str
    reason: str


class Claim(BaseModel):
    """A sourced, extracted/inferred assertion — the smallest unit the contradiction-detection loop operates on."""

    slug: str = Field(description="Unique page identifier, used by related_concepts/contradicted_by/key_facts.")
    claim_text: str = Field(description="Structured assertion text — not a verbatim copy of the source passage.")
    description: str = Field(
        default="",
        description="Short one-line summary for index.md entries (D23 §5.4) — LLM output, distinct from "
        "claim_text (which may be longer/more structured).",
    )
    source_ref: str = Field(description="Pointer into the Raw Source (document/passage position, or image link).")
    confidence: float = Field(ge=0.0, le=1.0, description="Factual-certainty score.")
    provenance_state: ProvenanceState
    related_concepts: list[str] = Field(default_factory=list, description="Slugs of linked Concept pages.")
    contradicted_by: list[ContradictionRef] = Field(default_factory=list)


class Concept(BaseModel):
    """A general topic/entity page — the fallback type when no more specific type applies."""

    slug: str = Field(description="Unique page identifier.")
    concept_title: str
    aliases: list[str] = Field(default_factory=list)
    tags: list[str] = Field(default_factory=list)
    summary: str = Field(
        description="LLM-generated summary — plain prose for a simple Concept, or markdown '## ' subsections "
        "when the topic has multiple distinct facets (e.g. history/mechanism/usage); not capped to one "
        "paragraph. Content, not metadata — persisted only in the page body, never frontmatter (see "
        "adapters/writers/markdown_writer.py).",
    )
    description: str = Field(
        default="",
        description="Short one-line summary for index.md entries (D23 §5.4) — LLM output, distinct from "
        "summary (which may be a full multi-section write-up).",
    )
    key_facts: list[str] = Field(
        default_factory=list,
        description="Slugs of related Claims — a backlink maintained incrementally by the Writer, not the LLM.",
    )
    related_pages: list[str] = Field(default_factory=list, description="Wikilinks to other Concept pages.")
    related_sources: list[str] = Field(default_factory=list, description="Source/provenance digest links.")


class Source(BaseModel):
    """A per-source navigation page, one per D10 Raw Source document (D21, reversing D20).

    Not a replacement for ``Claim.source_ref`` (which still points out of the wiki to the Raw Source itself,
    per D17) — this is an additional in-wiki entry point summarizing everything a source produced.
    """

    slug: str = Field(description="Unique page identifier — derived from the Raw Source's SourceRef.id.")
    source_title: str = Field(description="Human-readable title (source document title or filename).")
    source_path: str = Field(description="Location of the corresponding D10 Raw Source folder.")
    ingested_at: str = Field(description="Date this source was first compiled into the wiki.")
    summary: str = Field(
        description="Summary generated by recursive batch-reduce over Claims — plain prose or markdown "
        "'## ' subsections, not capped to one paragraph. Content, not metadata — persisted only in the page "
        "body, never frontmatter (see adapters/writers/markdown_writer.py)."
    )
    description: str = Field(
        default="",
        description="Short one-line summary for index.md entries (D23 §5.4) — deterministically generated by "
        "the Writer from summary on every write, never LLM output (same 'deterministic overrides LLM' "
        "treatment as source_ref anchoring, D17/D18/D22); any value passed in is overwritten. Plain "
        "discourse, like Claim/Concept.description — never a 'source_title: ...' composite; source_title is "
        "already the index entry's own [[slug]] link text.",
    )
    produced_claims: list[str] = Field(
        default_factory=list,
        description="Slugs of Claims this source produced — a backlink maintained incrementally by the "
        "Writer, not the LLM (same mechanism as Concept.key_facts, D18).",
    )
    produced_concepts: list[str] = Field(
        default_factory=list,
        description="Slugs of Concepts this source touched/updated — maintained the same way.",
    )
    related_pages: list[str] = Field(default_factory=list, description="Wikilinks to other pages.")
