"""Default Writer (docs/llm-yuki-v0.1-proposal/ARCHITECTURE.md §2.3): persists pages as OKF-style markdown.

Bundle layout::

    <bundle_root>/
        index.md         — regenerated after every write; lists all pages, grouped by type
        log.md            — append-only event log (§4.4)
        claims/<slug>.md
        concepts/<slug>.md

Body link sections (``## Related Pages`` / ``## Related Sources`` / ``## Key Facts``) are rendered
deterministically from frontmatter here, never independently generated by an LLM (§2.3.1) — this is what
keeps body and frontmatter from drifting apart without an extra consistency check. ``Concept.key_facts`` and
symmetric ``Claim.contradicted_by`` entries are maintained incrementally on every ``write_claim`` call (§2.3.2).
"""

from __future__ import annotations

import typing
from pathlib import Path

import yaml

from llm_yuki.domain.entities import Claim, Concept, ContradictionRef
from llm_yuki.ports.writer import Writer

_CLAIMS_DIR = "claims"
_CONCEPTS_DIR = "concepts"


class MarkdownWriter(Writer):
    """Filesystem-backed Writer — the only backend implemented/validated in this POC (D16)."""

    def __init__(self, bundle_root: Path | str) -> None:
        self._root = Path(bundle_root)
        (self._root / _CLAIMS_DIR).mkdir(parents=True, exist_ok=True)
        (self._root / _CONCEPTS_DIR).mkdir(parents=True, exist_ok=True)
        log_path = self._root / "log.md"
        if not log_path.exists():
            log_path.write_text("# Log\n\n", encoding="utf-8")

    # -- Writer interface ----------------------------------------------------

    def write_claim(self, claim: Claim) -> None:
        """Persist a Claim and maintain the backlinks it implies (Concept.key_facts, symmetric contradictions)."""
        self._write_claim_file(claim)
        self._maintain_claim_backlinks(claim)
        self._regenerate_index()

    def write_concept(self, concept: Concept) -> None:
        """Persist a Concept page."""
        self._write_concept_file(concept)
        self._regenerate_index()

    def read_claim(self, slug: str) -> Claim | None:
        """Read back a previously written Claim, or ``None`` if it does not exist."""
        path = self._claim_path(slug)
        if not path.exists():
            return None
        frontmatter, _ = self._read_page(path)
        return Claim.model_validate(frontmatter)

    def read_concept(self, slug: str) -> Concept | None:
        """Read back a previously written Concept, or ``None`` if it does not exist."""
        path = self._concept_path(slug)
        if not path.exists():
            return None
        frontmatter, _ = self._read_page(path)
        return Concept.model_validate(frontmatter)

    def list_pages(self) -> list[str]:
        """Return the slugs of all pages currently in the bundle."""
        claim_slugs = [p.stem for p in (self._root / _CLAIMS_DIR).glob("*.md")]
        concept_slugs = [p.stem for p in (self._root / _CONCEPTS_DIR).glob("*.md")]
        return sorted(claim_slugs + concept_slugs)

    # -- Log -------------------------------------------------------------------

    def append_log(self, event: str) -> None:
        """Append one line to the append-only ``log.md`` audit trail.

        Not yet called by anything — ``ErrorBook`` (which owns log events, see proposal ARCHITECTURE.md §4.4)
        is still a stub. Exposed now so the Writer's persistence surface is complete once that wiring exists.
        """
        log_path = self._root / "log.md"
        with log_path.open("a", encoding="utf-8") as f:
            f.write(f"- {event}\n")

    # -- Internals: paths --------------------------------------------------------

    def _claim_path(self, slug: str) -> Path:
        return self._root / _CLAIMS_DIR / f"{slug}.md"

    def _concept_path(self, slug: str) -> Path:
        return self._root / _CONCEPTS_DIR / f"{slug}.md"

    # -- Internals: low-level persistence (no backlink cascade) ------------------

    def _write_claim_file(self, claim: Claim) -> None:
        frontmatter: dict[str, object] = {"type": "Claim", **claim.model_dump(mode="json")}
        body = self._render_claim_body(claim)
        self._write_page(self._claim_path(claim.slug), frontmatter, body)

    def _write_concept_file(self, concept: Concept) -> None:
        frontmatter: dict[str, object] = {"type": "Concept", **concept.model_dump(mode="json")}
        body = self._render_concept_body(concept)
        self._write_page(self._concept_path(concept.slug), frontmatter, body)

    @staticmethod
    def _render_claim_body(claim: Claim) -> str:
        lines = [f"# {claim.slug}", "", claim.claim_text, ""]
        if claim.related_concepts:
            lines.append("## Related Pages")
            lines.extend(f"- [[{slug}]]" for slug in claim.related_concepts)
            lines.append("")
        if claim.source_ref:
            lines.append("## Related Sources")
            lines.append(f"- {claim.source_ref}")
            lines.append("")
        return "\n".join(lines)

    @staticmethod
    def _render_concept_body(concept: Concept) -> str:
        lines = [f"# {concept.concept_title}", "", concept.summary, ""]
        if concept.key_facts:
            lines.append("## Key Facts")
            lines.extend(f"- [[{slug}]]" for slug in concept.key_facts)
            lines.append("")
        if concept.related_pages:
            lines.append("## Related Pages")
            lines.extend(f"- [[{slug}]]" for slug in concept.related_pages)
            lines.append("")
        if concept.related_sources:
            lines.append("## Related Sources")
            lines.extend(f"- {src}" for src in concept.related_sources)
            lines.append("")
        return "\n".join(lines)

    @staticmethod
    def _write_page(path: Path, frontmatter: dict[str, object], body: str) -> None:
        yaml_block = yaml.safe_dump(frontmatter, sort_keys=False, allow_unicode=True)
        path.write_text(f"---\n{yaml_block}---\n\n{body}", encoding="utf-8")

    @staticmethod
    def _read_page(path: Path) -> tuple[dict[str, object], str]:
        raw = path.read_text(encoding="utf-8")
        _, _, rest = raw.partition("---\n")
        frontmatter_raw, _, body = rest.partition("\n---\n")
        loaded = yaml.safe_load(frontmatter_raw) or {}
        frontmatter = typing.cast("dict[str, object]", loaded)
        return frontmatter, body

    # -- Internals: backlink maintenance (§2.3.2) ---------------------------------

    def _maintain_claim_backlinks(self, claim: Claim) -> None:
        for concept_slug in claim.related_concepts:
            concept = self.read_concept(concept_slug)
            if concept is None:
                continue  # dangling link — a structural-validation concern, not this Writer's job
            if claim.slug not in concept.key_facts:
                concept.key_facts.append(claim.slug)
                self._write_concept_file(concept)

        for ref in claim.contradicted_by:
            other = self.read_claim(ref.slug)
            if other is None:
                continue
            if not any(existing.slug == claim.slug for existing in other.contradicted_by):
                other.contradicted_by.append(ContradictionRef(slug=claim.slug, reason=ref.reason))
                self._write_claim_file(other)

    # -- Internals: index.md ------------------------------------------------------

    def _regenerate_index(self) -> None:
        lines = ["# Index", "", "## Concepts"]
        lines.extend(f"- [[{slug}]]" for slug in sorted(p.stem for p in (self._root / _CONCEPTS_DIR).glob("*.md")))
        lines.extend(["", "## Claims"])
        lines.extend(f"- [[{slug}]]" for slug in sorted(p.stem for p in (self._root / _CLAIMS_DIR).glob("*.md")))
        lines.append("")
        (self._root / "index.md").write_text("\n".join(lines), encoding="utf-8")
