"""Default Writer (docs/llm-yuki-v0.1-proposal/ARCHITECTURE.md §2.3): persists pages as OKF-style markdown.

Bundle layout (D23 hierarchical index)::

    <bundle_root>/
        index.md              — root entry point: links to each type's own index.md
        log.md                — append-only event log (§4.4)
        claims/
            index.md          — full listing of Claim pages, one-line description each
            <slug>.md ...
        concepts/
            index.md
            <slug>.md ...
        sources/
            index.md
            <slug>.md ...

Body link sections (``## Related Pages`` / ``## Related Sources`` / ``## Key Facts`` / ``## Produced
Claims`` / ``## Produced Concepts``) are rendered deterministically from frontmatter here, never
independently generated by an LLM (§2.3.1) — this is what keeps body and frontmatter from drifting apart
without an extra consistency check. ``Concept.key_facts`` and symmetric ``Claim.contradicted_by`` entries are
maintained incrementally on every ``write_claim`` call (§2.3.2); as of D21, so are the source ``Source``'s
``produced_claims``/``produced_concepts``.
"""

from __future__ import annotations

import typing
from pathlib import Path

import yaml

from llm_yuki.domain.entities import Claim, Concept, ContradictionRef, Source
from llm_yuki.ports.writer import Writer

_CLAIMS_DIR = "claims"
_CONCEPTS_DIR = "concepts"
_SOURCES_DIR = "sources"


class MarkdownWriter(Writer):
    """Filesystem-backed Writer — the only backend implemented/validated in this POC (D16)."""

    def __init__(self, bundle_root: Path | str) -> None:
        self._root = Path(bundle_root)
        (self._root / _CLAIMS_DIR).mkdir(parents=True, exist_ok=True)
        (self._root / _CONCEPTS_DIR).mkdir(parents=True, exist_ok=True)
        (self._root / _SOURCES_DIR).mkdir(parents=True, exist_ok=True)
        log_path = self._root / "log.md"
        if not log_path.exists():
            log_path.write_text("# Log\n\n", encoding="utf-8")

    # -- Writer interface ----------------------------------------------------

    def write_claim(self, claim: Claim) -> None:
        """Persist a Claim and maintain the backlinks it implies (Concept.key_facts, source Source's
        produced_claims/produced_concepts, symmetric contradictions).
        """
        self._write_claim_file(claim)
        self._maintain_claim_backlinks(claim)
        self._regenerate_index()

    def write_concept(self, concept: Concept) -> None:
        """Persist a Concept page."""
        self._write_concept_file(concept)
        self._regenerate_index()

    def write_source(self, source: Source) -> None:
        """Persist a Source page (D21)."""
        self._write_source_file(source)
        self._regenerate_index()

    def read_claim(self, slug: str) -> Claim | None:
        """Read back a previously written Claim, or ``None`` if it does not exist."""
        path = self._claim_path(slug)
        if not path.exists():
            return None
        frontmatter, _ = self._read_page(path)
        return Claim.model_validate(frontmatter)

    def read_concept(self, slug: str) -> Concept | None:
        """Read back a previously written Concept, or ``None`` if it does not exist."""
        path = self._concept_path(slug)
        if not path.exists():
            return None
        frontmatter, _ = self._read_page(path)
        return Concept.model_validate(frontmatter)

    def read_source(self, slug: str) -> Source | None:
        """Read back a previously written Source, or ``None`` if it does not exist."""
        path = self._source_path(slug)
        if not path.exists():
            return None
        frontmatter, _ = self._read_page(path)
        return Source.model_validate(frontmatter)

    def list_pages(self) -> list[str]:
        """Return the slugs of all pages currently in the bundle, across all three core types."""
        return sorted(
            self._page_slugs(_CLAIMS_DIR) + self._page_slugs(_CONCEPTS_DIR) + self._page_slugs(_SOURCES_DIR)
        )

    def _page_slugs(self, dir_name: str) -> list[str]:
        """Slugs of content pages in a type directory — excludes that directory's own ``index.md`` (D23)."""
        return [p.stem for p in (self._root / dir_name).glob("*.md") if p.stem != "index"]

    # -- Log -------------------------------------------------------------------

    def append_log(self, event: str) -> None:
        """Append one line to the append-only ``log.md`` audit trail (§4.4).

        Called by ``ErrorBook.update_error_book``/``verify_and_close`` — see ``domain/error_book.py``.
        """
        log_path = self._root / "log.md"
        with log_path.open("a", encoding="utf-8") as f:
            f.write(f"- {event}\n")

    # -- Internals: paths --------------------------------------------------------

    def _claim_path(self, slug: str) -> Path:
        return self._root / _CLAIMS_DIR / f"{slug}.md"

    def _concept_path(self, slug: str) -> Path:
        return self._root / _CONCEPTS_DIR / f"{slug}.md"

    def _source_path(self, slug: str) -> Path:
        return self._root / _SOURCES_DIR / f"{slug}.md"

    # -- Internals: low-level persistence (no backlink cascade) ------------------

    def _write_claim_file(self, claim: Claim) -> None:
        frontmatter: dict[str, object] = {"type": "Claim", **claim.model_dump(mode="json")}
        body = self._render_claim_body(claim)
        self._write_page(self._claim_path(claim.slug), frontmatter, body)

    def _write_concept_file(self, concept: Concept) -> None:
        frontmatter: dict[str, object] = {"type": "Concept", **concept.model_dump(mode="json")}
        body = self._render_concept_body(concept)
        self._write_page(self._concept_path(concept.slug), frontmatter, body)

    def _write_source_file(self, source: Source) -> None:
        frontmatter: dict[str, object] = {"type": "Source", **source.model_dump(mode="json")}
        body = self._render_source_body(source)
        self._write_page(self._source_path(source.slug), frontmatter, body)

    @staticmethod
    def _render_claim_body(claim: Claim) -> str:
        lines = [f"# {claim.slug}", "", claim.claim_text, ""]
        if claim.related_concepts:
            lines.append("## Related Pages")
            lines.extend(f"- [[{slug}]]" for slug in claim.related_concepts)
            lines.append("")
        if claim.source_ref:
            lines.append("## Related Sources")
            lines.append(f"- {claim.source_ref}")
            lines.append("")
        return "\n".join(lines)

    @staticmethod
    def _render_concept_body(concept: Concept) -> str:
        lines = [f"# {concept.concept_title}", "", concept.summary, ""]
        if concept.key_facts:
            lines.append("## Key Facts")
            lines.extend(f"- [[{slug}]]" for slug in concept.key_facts)
            lines.append("")
        if concept.related_pages:
            lines.append("## Related Pages")
            lines.extend(f"- [[{slug}]]" for slug in concept.related_pages)
            lines.append("")
        if concept.related_sources:
            lines.append("## Related Sources")
            lines.extend(f"- {src}" for src in concept.related_sources)
            lines.append("")
        return "\n".join(lines)

    @staticmethod
    def _render_source_body(source: Source) -> str:
        lines = [f"# {source.source_title}", "", source.summary, ""]
        if source.produced_claims:
            lines.append("## Produced Claims")
            lines.extend(f"- [[{slug}]]" for slug in source.produced_claims)
            lines.append("")
        if source.produced_concepts:
            lines.append("## Produced Concepts")
            lines.extend(f"- [[{slug}]]" for slug in source.produced_concepts)
            lines.append("")
        if source.related_pages:
            lines.append("## Related Pages")
            lines.extend(f"- [[{slug}]]" for slug in source.related_pages)
            lines.append("")
        lines.append("## Source")
        lines.append(f"- {source.source_path}")
        lines.append("")
        return "\n".join(lines)

    @staticmethod
    def _write_page(path: Path, frontmatter: dict[str, object], body: str) -> None:
        yaml_block = yaml.safe_dump(frontmatter, sort_keys=False, allow_unicode=True)
        path.write_text(f"---\n{yaml_block}---\n\n{body}", encoding="utf-8")

    @staticmethod
    def _read_page(path: Path) -> tuple[dict[str, object], str]:
        raw = path.read_text(encoding="utf-8")
        _, _, rest = raw.partition("---\n")
        frontmatter_raw, _, body = rest.partition("\n---\n")
        loaded = yaml.safe_load(frontmatter_raw) or {}
        frontmatter = typing.cast("dict[str, object]", loaded)
        return frontmatter, body

    # -- Internals: backlink maintenance (§2.3.2, D21) ----------------------------

    def _maintain_claim_backlinks(self, claim: Claim) -> None:
        for concept_slug in claim.related_concepts:
            concept = self.read_concept(concept_slug)
            if concept is None:
                continue  # dangling link — a structural-validation concern, not this Writer's job
            if claim.slug not in concept.key_facts:
                concept.key_facts.append(claim.slug)
                self._write_concept_file(concept)

        for ref in claim.contradicted_by:
            other = self.read_claim(ref.slug)
            if other is None:
                continue
            if not any(existing.slug == claim.slug for existing in other.contradicted_by):
                other.contradicted_by.append(ContradictionRef(slug=claim.slug, reason=ref.reason))
                self._write_claim_file(other)

        self._maintain_source_backlinks(claim)

    def _maintain_source_backlinks(self, claim: Claim) -> None:
        """Add ``claim.slug``/its ``related_concepts`` to the source Source page's backlinks (D21).

        The source Source page is identified from ``claim.source_ref``'s leading ``<source-slug>`` segment
        (everything before an optional ``#locator``) — the same convention ``LLMExtractor`` is prompted to
        produce ``source_ref`` in. If that Source page hasn't been written yet, this is a dangling link, same
        treatment as an unresolved ``related_concepts`` target above: skipped, not this Writer's job to fix.
        """
        source_slug = claim.source_ref.split("#", 1)[0]
        source = self.read_source(source_slug)
        if source is None:
            return

        changed = False
        if claim.slug not in source.produced_claims:
            source.produced_claims.append(claim.slug)
            changed = True
        for concept_slug in claim.related_concepts:
            if concept_slug not in source.produced_concepts:
                source.produced_concepts.append(concept_slug)
                changed = True
        if changed:
            self._write_source_file(source)

    # -- Internals: index.md (D23 hierarchical layout) ----------------------------

    def _regenerate_index(self) -> None:
        self._write_type_index(_CLAIMS_DIR, "Claims", self._claim_index_entries())
        self._write_type_index(_CONCEPTS_DIR, "Concepts", self._concept_index_entries())
        self._write_type_index(_SOURCES_DIR, "Sources", self._source_index_entries())
        self._write_root_index()

    def _claim_index_entries(self) -> list[tuple[str, str]]:
        entries = []
        for slug in sorted(self._page_slugs(_CLAIMS_DIR)):
            claim = self.read_claim(slug)
            if claim is not None:
                entries.append((slug, claim.claim_text))
        return entries

    def _concept_index_entries(self) -> list[tuple[str, str]]:
        entries = []
        for slug in sorted(self._page_slugs(_CONCEPTS_DIR)):
            concept = self.read_concept(slug)
            if concept is not None:
                entries.append((slug, f"{concept.concept_title}: {concept.summary}"))
        return entries

    def _source_index_entries(self) -> list[tuple[str, str]]:
        entries = []
        for slug in sorted(self._page_slugs(_SOURCES_DIR)):
            source = self.read_source(slug)
            if source is not None:
                entries.append((slug, f"{source.source_title}: {source.summary}"))
        return entries

    def _write_type_index(self, dir_name: str, label: str, entries: list[tuple[str, str]]) -> None:
        lines = [f"# {label} Index", ""]
        lines.extend(f"- [[{slug}]] — {description}" for slug, description in entries)
        lines.append("")
        (self._root / dir_name / "index.md").write_text("\n".join(lines), encoding="utf-8")

    def _write_root_index(self) -> None:
        lines = [
            "# Index",
            "",
            "## Claims",
            f"- [Claims Index]({_CLAIMS_DIR}/index.md)",
            "",
            "## Concepts",
            f"- [Concepts Index]({_CONCEPTS_DIR}/index.md)",
            "",
            "## Sources",
            f"- [Sources Index]({_SOURCES_DIR}/index.md)",
            "",
        ]
        (self._root / "index.md").write_text("\n".join(lines), encoding="utf-8")
